# Generated by Django 5.2.11 on 2026-02-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"verbose_name": "Board", "verbose_name_plural": "Boards"},
        ),
        migrations.AlterModelOptions(
            name="card",
            options={"verbose_name": "Card", "verbose_name_plural": "Cards"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="list",
            options={"verbose_name": "List", "verbose_name_plural": "Lists"},
        ),
        migrations.AlterModelTable(
            name="board",
            table="board",
        ),
        migrations.AlterModelTable(
            name="card",
            table="card",
        ),
        migrations.AlterModelTable(
            name="comment",
            table="comment",
        ),
        migrations.AlterModelTable(
            name="list",
            table="list",
        ),
    ]
