# Generated by Django 5.2.11 on 2026-02-19 12:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.board_bg_upload_path
            ),
        ),
    ]
