# Generated by Django 5.2.11 on 2026-03-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_board_background_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="card",
            unique_together={("list", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="list",
            unique_together={("board", "order")},
        ),
    ]
