# Generated by Django 5.2.11 on 2026-07-08 — manually adjusted to avoid FK violation

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_workspace_for_boards(apps, schema_editor):
    """
    For any existing boards without a workspace, create a default workspace
    and assign it to those boards. This handles the data migration safely.
    """
    Board = apps.get_model('api', 'Board')
    Workspace = apps.get_model('api', 'Workspace')

    boards_without_workspace = Board.objects.filter(workspace__isnull=True)
    if boards_without_workspace.exists():
        # Group orphaned boards by owner and create one workspace per owner
        owner_ids = boards_without_workspace.values_list('owner_id', flat=True).distinct()
        for owner_id in owner_ids:
            ws = Workspace.objects.create(
                name='My Workspace',
                owner_id=owner_id,
            )
            boards_without_workspace.filter(owner_id=owner_id).update(workspace=ws)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_card_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Update Board.members related_name
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='board_memberships', to=settings.AUTH_USER_MODEL),
        ),
        # Step 2: Create the Workspace table first
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'workspace',
                'ordering': ['-updated_at'],
            },
        ),
        # Step 3: Add workspace as nullable so existing rows don't violate FK
        migrations.AddField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='boards',
                to='api.workspace',
            ),
        ),
        # Step 4: Create default workspaces for any orphaned boards (data migration)
        migrations.RunPython(
            create_default_workspace_for_boards,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 5: Make workspace non-nullable (enforce the constraint)
        migrations.AlterField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='boards',
                to='api.workspace',
            ),
        ),
    ]
